version: '3.5'
services: 
  nginx_prod:
    container_name: reverse-proxy_nginx_prod
    build: nginx/
    ports:
      - 80:80
    environment:
      - ENV=prod
    networks:
      - prod
networks:
  prod:
    external:
      name: prod
    