version: '3.5'
services: 
  nginx_test:
    container_name: reverse-proxy_nginx_test
    build: nginx/
    ports:
      - 81:80
    environment:
      - ENV=test 
    networks:
      - test
networks:
  test:
    name: test
    driver: bridge
