version: '3.5'
services: 
  app1_local:
    container_name: reverse_proxy_app1_local
    build: app1/
    environment:
      - ENV=local
    networks:
      - local
  app2_local:
    container_name: reverse_proxy_app2_local
    build: app2/
    environment:
      - ENV=local
    networks:
      - local
  nginx_local:
    depends_on: 
      - app1_local
      - app2_local
    container_name: reverse_proxy_nginx_local
    build: nginx/
    environment:
      - ENV=local
    networks:
      - local
  test_local:
    container_name: reverse_proxy_test_local
    build: test/
    networks:
      - local
networks:
  local:
    external:
      name: local
    